<<<<<<< backend/api/migrations/0001_initial.py
# Generated by Django 2.2.6 on 2020-09-24 08:39

from django.db import migrations, models
=======
# Generated by Django 3.0.5 on 2020-09-24 08:07

from django.db import migrations, models
import djongo.models.fields
>>>>>>> backend/api/migrations/0001_initial.py


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField()),
                ('category', models.CharField(max_length=400)),
                ('main', models.CharField(max_length=400)),
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('data', djongo.models.fields.JSONField()),
            ],
        ),
    ]
