# Generated by Django 3.1.1 on 2020-09-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('item_code', models.CharField(max_length=6)),
                ('item_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('buy_date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimulationBreakdown',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('item_code', models.CharField(max_length=6)),
                ('item_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('buy_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('sell_date', models.DateField()),
            ],
        ),
    ]
