# Generated by Django 3.0.5 on 2020-09-20 08:04

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('item_code', models.CharField(max_length=6)),
                ('item_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('buy_date', models.DateTimeField(default=datetime.datetime.now)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimulationBreakdown',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('item_code', models.CharField(max_length=6)),
                ('item_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('buy_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('sell_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
