# Generated by Django 3.1.1 on 2020-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='buy_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='simulationbreakdown',
            name='sell_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
