# Generated by Django 3.1.1 on 2020-09-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_auto_20200915_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationbreakdown',
            name='buy_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='simulationbreakdown',
            name='sell_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
