# Generated by Django 3.1.1 on 2020-09-15 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_auto_20200915_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='buy_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='simulationbreakdown',
            name='sell_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
