# Generated by Django 3.0.5 on 2020-10-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestmodel',
            name='strategy',
            field=models.IntegerField(default=1),
        ),
    ]
