# Generated by Django 3.0.5 on 2020-10-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_backtestmodel_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestmodel',
            name='rebalance',
            field=models.IntegerField(default=1),
        ),
    ]
